### ISSUE TITLE
NullPointerException for a non initialized PickedState in PluggableRenderContext

### ISSUE THREAD

**Issue by bracco23** [jrtom/jung#48]
I was tryin to display a single graph but it stops me when i try to execute for the first time this code:

>    Forest<String, String> g = new DelegateForest<String, String>();
     [...]
     Layout<String, String> l = new TreeLayout<String, String>(g);
     BasicVisualizationServer<String, String> vv = new BasicVisualizationServer<String, String>(l);
     [...]
     vv.setPreferredSize(graphPane.getSize());
     graphPane.add(vv, BorderLayout.CENTER);

It basically creates a Forest, fills the Forest (code not shown), and uses a default TreeLayout to visualize it in a BasicVisualizationServer. version 2.0.1 worked fine, after updating at 2.1 it gives me a NullPointerException.

After a bit of debug I discovered that the PluggableRenderContext that vv uses as a default doesn't initialize the two PickedState, vetrtex and edge, and it hangs exactly on the call to the the vertexPickedState.

This is the exception: 

`java.lang.NullPointerException
	at edu.uci.ics.jung.visualization.renderers.BasicVertexLabelRenderer.labelVertex(BasicVertexLabelRenderer.java:84)
	at edu.uci.ics.jung.visualization.renderers.BasicRenderer.renderVertexLabel(BasicRenderer.java:74)
	at edu.uci.ics.jung.visualization.renderers.BasicRenderer.render(BasicRenderer.java:59)
	at edu.uci.ics.jung.visualization.BasicVisualizationServer.renderGraph(BasicVisualizationServer.java:348)
	at edu.uci.ics.jung.visualization.BasicVisualizationServer.paintComponent(BasicVisualizationServer.java:303)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by Claus1** [comment]
Found the same. 2.1 is buggy even on trivial example.

**Comment by jrtom** [comment]
This issue was raised in #44 and fixed in #45 (merged on 1 April).  We'll put a new bugfix release  out soon; in the meantime you can download the latest code to avoid this issue.
