### ISSUE TITLE
NullPointerException: edu.uci.ics.jung.graph.util.Context#hashCode

### ISSUE THREAD

**Issue by uwolfer** [jrtom/jung#59]
```
java.lang.NullPointerException: null
	at edu.uci.ics.jung.graph.util.Context.hashCode(Context.java:38)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at edu.uci.ics.jung.graph.util.DefaultParallelEdgeIndexFunction.getIndex(DefaultParallelEdgeIndexFunction.java:60)
	at edu.uci.ics.jung.visualization.renderers.BasicEdgeLabelRenderer.labelEdge(BasicEdgeLabelRenderer.java:81)
	at edu.uci.ics.jung.visualization.renderers.BasicRenderer.renderEdgeLabel(BasicRenderer.java:82)
	at edu.uci.ics.jung.visualization.renderers.BasicRenderer.render(BasicRenderer.java:42)
	at edu.uci.ics.jung.visualization.BasicVisualizationServer.renderGraph(BasicVisualizationServer.java:348)
	at edu.uci.ics.jung.visualization.BasicVisualizationServer.paintComponent(BasicVisualizationServer.java:303)
```

I think the issue is that `Context#getInstance` is called with a `null` `Graph` initiated at BasicEdgeLabelRenderer.java:81.

```
	  at edu.uci.ics.jung.graph.util.Context.getInstance(Context.java:31)
	  at edu.uci.ics.jung.graph.util.DefaultParallelEdgeIndexFunction.getIndex(DefaultParallelEdgeIndexFunction.java:60)
	  at edu.uci.ics.jung.visualization.renderers.BasicEdgeLabelRenderer.labelEdge(BasicEdgeLabelRenderer.java:81)
	  at edu.uci.ics.jung.visualization.renderers.BasicRenderer.renderEdgeLabel(BasicRenderer.java:82)
	  at edu.uci.ics.jung.visualization.renderers.BasicRenderer.render(BasicRenderer.java:42)
	  at edu.uci.ics.jung.visualization.BasicVisualizationServer.renderGraph(BasicVisualizationServer.java:348)
	  at edu.uci.ics.jung.visualization.BasicVisualizationServer.paintComponent(BasicVisualizationServer.java:303)
```

Using version 2.1.

**Comment by jrtom** [comment]
Hmm.  Haven't looked closely at this yet, but it looks like the same issue as here: https://github.com/jrtom/jung/pull/50

**Comment by uwolfer** [comment]
@jrtom: Thanks, this looks like (almost) the same. Any plans to publish a bugfix release soon?
